# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2605607a76967fb62330c5761d8c3d6be21f00f49aa6066d0a2a17cb61404deb842ff8d17a258cb20daef6983f379c57c53d4f359f243f0b9c959b2a0f560308

test:
  secret_key_base: 75b1293edab8b944175e21dbadc99efa29ba0aef3213578f8b2dc108e554b9bdbb1e19f0ef2018ac229a9f143e37b0c947d364f9763c1c84d86dd5d41832ab12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
